### ISSUE TITLE
unhandledRejection TypeError: Cannot read property 'collection' of undefined

### ISSUE THREAD

**Issue by gannons** [passuied/mocha-xunit-reporter#4]
When running mocha with version `2.1.0` I see

    unhandledRejection TypeError: Cannot read property 'collection' of undefined
        at lastCollection (/Users/gannons/Development/my-app/test-scripts/node_modules/mocha-xunit-reporter/index.js:80:48)
        at MochaXUnitReporter.<anonymous> (/Users/gannons/Development/my-app/test-scripts/node_modules/mocha-xunit-reporter/index.js:115:7)
        at Runner.emit (events.js:203:15)
        at Runner.fail (/Users/gannons/Development/my-app/test-scripts/node_modules/mocha/lib/runner.js:310:8)
        at Runner.failHook (/Users/gannons/Development/my-app/test-scripts/node_modules/mocha/lib/runner.js:348:8)
        at /Users/gannons/Development/my-app/test-scripts/node_modules/mocha/lib/runner.js:422:14
        at done (/Users/gannons/Development/my-app/test-scripts/node_modules/mocha/lib/runnable.js:335:5)
        at /Users/gannons/Development/my-app/test-scripts/node_modules/mocha/lib/runnable.js:406:11
        at process._tickCallback (internal/process/next_tick.js:68:7)

If I revert back to `2.0.0` this issue goes away.

This is not an issue for me as I reverted to `mocha-junit-reporter` but FYI.

**Comment by john-ro** [comment]
I actually ran into this as well. @gannons this is probably happening because one of your hooks (before, beforeEach, after, afterEach) is sitting outside the test suites and they're failing, and the library isn't handling that gracefully

**Comment by gannons** [comment]
That is the case. My pseudo code setup is

    before(async function () {
      ....
    }
    
    after(async function() {
      ....
    }
    
    describe('test suite', () => {
      it('test', async function() {
        ....
      })
    })

**Comment by john-ro** [comment]
@gannons yep I'm able to replicate with that setup. I'm currently working on a fix now so you can expect to see an update soon.

**Comment by passuied** [comment]
Issue resolved in https://github.com/passuied/mocha-xunit-reporter/pull/5

**Comment by passuied** [comment]
Version 2.1.1 with fix published. Closing issue
